FROM scratch
# new image

# instruction set group 1

ARG RELEASE
ARG LAUNCHPAD_BUILD_ARCH
LABEL org.opencontainers.image.ref.name=ubuntu
LABEL org.opencontainers.image.version=22.04
ADD file:36d444e2cede3abe58191dcf28890b874c0908f5259bf7e8855338555701c4c5 /
CMD ["/bin/bash"]

# end of image: ubuntu:latest (id:  tags: ubuntu:latest)
